/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/new/hhh.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Hhh(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("./models/new/hhh.glb" )
  const { actions } = useAnimations(animations, group)
  console.log(actions,'actions')
  if(actions.Fly){
    actions.Fly.play()
  }
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Eagle" scale={0.01}>
          <group name="Eagle(0)">
            <group name="Bip01" position={[0, 74.957, -5.785]} rotation={[-0.106, -1.571, 0]}>
              <primitive object={nodes.Bip01_Pelvis} />
              <skinnedMesh name="Eagle(1)" geometry={nodes['Eagle(1)'].geometry} material={materials.lambert4SG} skeleton={nodes['Eagle(1)'].skeleton} />
            </group>
          </group>
        </group>
        <group name="Armature" position={[0, 1.12, -0.392]} rotation={[1.304, 0, 0]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="hey" geometry={nodes.hey.geometry} material={materials.Fogel_Mat} skeleton={nodes.hey.skeleton} />
        </group>
        <group name="Sun" position={[0.112, 10.039, -4.177]} rotation={[-0.576, 0, 0]} />
        <group name="Lamp" position={[-3.872, 4.316, 3.325]} rotation={[1.89, 0.881, -2.045]} />
        <group name="Camera" position={[7.481, 5.344, 6.508]} rotation={[1.235, 0.323, -0.762]} />
        <group name="Lamp001" position={[-0.947, 1.868, -0.815]} rotation={[1.89, 0.881, -2.045]} />
        <group name="Lamp002" position={[1.281, 4.086, -1.573]} rotation={[1.89, 0.881, -2.045]} />
        <group name="Sun001" position={[0.112, -0.356, -4.177]} rotation={[-2.189, 0, 0]} />
        <group name="metarig" scale={3.146}>
          <group name="spine003" position={[0, 0.084, -0.045]} rotation={[1.406, 0, 0]}>
            <group name="spine002" rotation={[-2.863, 0, 0]}>
              <group name="spine001" position={[0, 0.031, 0]} rotation={[-0.018, 0, 0]}>
                <group name="spine" position={[0, 0.028, 0]} rotation={[-0.135, 0, 0]}>
                  <group name="t_featherL" position={[0.011, -0.002, 0]} rotation={[0.001, 0.006, -0.166]} />
                  <group name="t_featherR" position={[-0.011, -0.002, 0]} rotation={[0.001, -0.006, 0.166]} />
                </group>
              </group>
            </group>
            <group name="spine004" position={[0, 0.026, 0]} rotation={[-0.132, 0, 0]}>
              <group name="spine005" position={[0, 0.031, 0]} rotation={[-0.454, 0, 0]}>
                <group name="shoulderL" position={[0.001, 0.002, 0.014]} rotation={[-0.851, 1.253, -0.596]}>
                  <group name="WingL" position={[0.014, 0.043, -0.004]} rotation={[1.493, 0.332, -0.195]}>
                    <group name="Wing001L" position={[0, 0.04, 0]} rotation={[-0.013, -0.007, 0.119]}>
                      <group name="Wing002L" position={[0, 0.044, 0]} rotation={[-0.013, 0.005, -0.336]}>
                        <group name="w_feather001L" position={[-0.016, 0.066, 0.006]} rotation={[-0.076, 0.155, 0.146]} />
                        <group name="w_feather002L" position={[0.028, 0.034, 0]} rotation={[-0.019, 0.001, -0.141]} />
                      </group>
                      <group name="w_feather003L" position={[0.017, 0.024, 0.001]} rotation={[0.072, 0.014, -1.045]} />
                    </group>
                    <group name="w_feather004L" position={[0.015, 0.028, 0.004]} rotation={[-0.027, 0.021, -1.4]} />
                  </group>
                </group>
                <group name="spine006" position={[0, 0.026, 0]} rotation={[-0.261, 0, 0]}>
                  <group name="neck001" position={[0, 0.022, 0]} rotation={[-0.091, 0, 0]}>
                    <group name="neck002" position={[0, 0.009, 0]} rotation={[-0.121, 0, 0]}>
                      <group name="head" position={[0, 0.007, 0]} rotation={[0.695, 0, 0]}>
                        <group name="beak001T" position={[0, 0.023, 0.004]} rotation={[0.453, 0, 0]}>
                          <group name="beak002T" position={[0, 0.022, 0]} rotation={[0.38, 0, 0]} />
                        </group>
                        <group name="beak_001B" position={[0, 0.022, 0.006]} rotation={[0.533, 0, 0]}>
                          <group name="beak002B" position={[0, 0.021, 0]} rotation={[0.204, 0, 0]} />
                          <group name="tongue001L" position={[0, 0.009, 0.002]} rotation={[-0.382, 0, 0]}>
                            <group name="tongue002L" position={[0, 0.005, 0]} rotation={[0.436, 0, 0]}>
                              <group name="tongue003L" position={[0, 0.003, 0]} rotation={[-0.059, 0, 0]} />
                            </group>
                          </group>
                        </group>
                        <group name="eyeL" position={[0.006, 0.02, -0.002]} rotation={[-2.613, 0, -1.764]} />
                        <group name="eyeR" position={[-0.006, 0.02, -0.002]} rotation={[-2.613, 0, 1.764]} />
                        <group name="n_feather001L" position={[0.01, -0.005, -0.011]} rotation={[2.914, 0.028, -0.166]} />
                        <group name="n_feather001R" position={[-0.01, -0.005, -0.011]} rotation={[2.914, -0.028, 0.166]} />
                        <group name="skull006L" position={[0.003, 0.011, 0.002]} rotation={[-1.324, -0.484, -1.9]} />
                        <group name="skull006R" position={[-0.003, 0.011, 0.002]} rotation={[-1.324, 0.484, 1.9]} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="shoulderR" position={[-0.001, 0.002, 0.014]} rotation={[-0.851, -1.253, 0.596]}>
                  <group name="WingR" position={[-0.014, 0.043, -0.004]} rotation={[1.493, -0.332, 0.195]}>
                    <group name="Wing001R" position={[0, 0.04, 0]} rotation={[-0.013, 0.007, -0.119]}>
                      <group name="Wing002R" position={[0, 0.044, 0]} rotation={[-0.013, -0.005, 0.336]}>
                        <group name="w_feather001R" position={[0.016, 0.066, 0.006]} rotation={[-0.076, -0.155, -0.146]} />
                        <group name="w_feather002R" position={[-0.028, 0.034, 0]} rotation={[-0.019, -0.001, 0.141]} />
                      </group>
                      <group name="w_feather003R" position={[-0.017, 0.024, 0.001]} rotation={[0.072, -0.014, 1.045]} />
                    </group>
                    <group name="w_feather004R" position={[-0.015, 0.028, 0.004]} rotation={[-0.027, -0.021, 1.4]} />
                  </group>
                </group>
              </group>
              <group name="pelvisL" rotation={[2.97, 0.539, -1.778]} />
              <group name="pelvisR" rotation={[2.97, -0.539, 1.778]} />
              <group name="thighL" position={[0.015, 0.008, 0.018]} rotation={[2.093, 0, 0]}>
                <group name="shinL" position={[0, 0.036, 0]} rotation={[-0.61, 0, 0]}>
                  <group name="footL" position={[0, 0.034, 0]} rotation={[-0.644, 0, 0]}>
                    <group name="toeL" position={[0, 0.006, 0]} rotation={[2.703, 0, Math.PI]}>
                      <group name="toes_parentL" rotation={[-0.022, 0, 0]}>
                        <group name="t_ring001L" position={[-0.003, -0.001, -0.001]} rotation={[0.166, -0.002, 0.31]}>
                          <group name="t_ring002L" position={[0, 0.011, 0]} rotation={[-0.123, 0.051, 0]}>
                            <group name="t_ring003L" position={[0, 0.007, 0]} rotation={[-0.197, 0.075, -0.006]} />
                          </group>
                        </group>
                        <group name="t_index001L" position={[0.003, -0.001, -0.001]} rotation={[0.165, 0, -0.272]}>
                          <group name="t_index002L" position={[0, 0.011, 0]} rotation={[-0.099, -0.061, -0.002]}>
                            <group name="t_index003L" position={[0, 0.01, 0]} rotation={[-0.147, -0.036, 0.008]} />
                          </group>
                        </group>
                        <group name="t_middle001L" position={[0, 0.002, -0.001]} rotation={[0.165, 0, 0]}>
                          <group name="t_middle002L" position={[0, 0.016, 0]} rotation={[-0.127, 0, 0]}>
                            <group name="t_middle003L" position={[0, 0.01, 0]} rotation={[-0.203, 0, 0]} />
                          </group>
                        </group>
                      </group>
                      <group name="t_thumb001L" position={[0.001, -0.008, -0.003]} rotation={[-3.081, 0, -0.055]}>
                        <group name="t_thumb002L" position={[0, 0.009, 0]} rotation={[0.272, 0.015, 0.004]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="thighR" position={[-0.015, 0.008, 0.018]} rotation={[2.093, 0, 0]}>
                <group name="shinR" position={[0, 0.036, 0]} rotation={[-0.61, 0, 0]}>
                  <group name="footR" position={[0, 0.034, 0]} rotation={[-0.644, 0, 0]}>
                    <group name="toeR" position={[0, 0.006, 0]} rotation={[2.703, 0, -Math.PI]}>
                      <group name="toes_parentR" rotation={[-0.022, 0, 0]}>
                        <group name="t_ring001R" position={[0.003, -0.001, -0.001]} rotation={[0.166, 0.002, -0.31]}>
                          <group name="t_ring002R" position={[0, 0.011, 0]} rotation={[-0.123, -0.051, 0]}>
                            <group name="t_ring003R" position={[0, 0.007, 0]} rotation={[-0.197, -0.075, 0.006]} />
                          </group>
                        </group>
                        <group name="t_index001R" position={[-0.003, -0.001, -0.001]} rotation={[0.165, 0, 0.272]}>
                          <group name="t_index002R" position={[0, 0.011, 0]} rotation={[-0.099, 0.061, 0.002]}>
                            <group name="t_index003R" position={[0, 0.01, 0]} rotation={[-0.147, 0.036, -0.008]} />
                          </group>
                        </group>
                        <group name="t_middle001R" position={[0, 0.002, -0.001]} rotation={[0.165, 0, 0]}>
                          <group name="t_middle002R" position={[0, 0.016, 0]} rotation={[-0.127, 0, 0]}>
                            <group name="t_middle003R" position={[0, 0.01, 0]} rotation={[-0.203, 0, 0]} />
                          </group>
                        </group>
                      </group>
                      <group name="t_thumb001R" position={[-0.001, -0.008, -0.003]} rotation={[-3.081, 0, 0.055]}>
                        <group name="t_thumb002R" position={[0, 0.009, 0]} rotation={[0.272, -0.015, -0.004]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hhh.glb')
